import "./globals.css";
import ArticleWrapper from "./components/articlewrapper";


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
      <ArticleWrapper/>
      <div>{children}</div>
      </body>
    </html>
  );
}
